# Generated by Django 5.1.7 on 2025-03-19 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbase_app', '0002_alter_currencyexchangerate_valuation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='exchanged_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_exc', to='backbase_app.currency'),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='source_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_src', to='backbase_app.currency'),
        ),
    ]
