# Generated by Django 5.1.7 on 2025-03-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbase_app', '0003_alter_currencyexchangerate_exchanged_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='valuation_date',
            field=models.DateField(auto_now=True, db_index=True),
        ),
    ]
