# Generated by Django 5.1.7 on 2025-03-19 19:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbase_app', '0005_alter_currencyexchangerate_valuation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='valuation_date',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
    ]
