# Generated by Django 5.1.7 on 2025-03-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbase_app', '0008_alter_currencyexchangerate_valuation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('priority', models.IntegerField(default=0)),
                ('activated', models.BooleanField(default=True)),
            ],
        ),
    ]
