# Generated by Django 5.1.7 on 2025-03-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbase_app', '0009_proveedorexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorexchange',
            name='id_name',
            field=models.IntegerField(db_index=True, default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedorexchange',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
