# Generated by Django 5.1.7 on 2025-03-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbase_app', '0010_proveedorexchange_id_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorexchange',
            name='id_name',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
