# Generated by Django 5.1.7 on 2025-03-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbase_app', '0011_alter_proveedorexchange_id_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorexchange',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
