# Generated by Django 5.1.7 on 2025-03-22 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbase_app', '0012_alter_proveedorexchange_priority'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProveedorExchange',
            new_name='ProviderExchange',
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='valuation_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date(2025, 3, 22)),
        ),
    ]
