# Generated by Django 5.1.7 on 2025-03-28 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbase_app', '0013_rename_proveedorexchange_providerexchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='valuation_date',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='currencyexchangerate',
            unique_together={('source_currency', 'exchanged_currency', 'valuation_date')},
        ),
    ]
