# Generated by Django 5.1.7 on 2025-03-31 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbase_app', '0014_alter_currencyexchangerate_valuation_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyexchangerate',
            unique_together=set(),
        ),
    ]
