# Generated by Django 5.1.7 on 2025-03-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backbase_app', '0015_alter_currencyexchangerate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='rate_value',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
