# Generated by Django 5.1.7 on 2025-03-31 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backbase_app', '0016_alter_currencyexchangerate_rate_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyexchangerate',
            unique_together={('source_currency', 'exchanged_currency', 'valuation_date')},
        ),
    ]
